
# version: '3.1'
# services:
#   mongo:
#     image: mongo
#     restart: unless-stopped
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: osher
#       MONGO_INITDB_ROOT_PASSWORD: 123456

#   mongo-express:
#     image: mongo-express
#     restart: unless-stopped
#     ports:
#       - 8081:8081
#       - 27017:27017
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: osher
#       ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: osher
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  mongo_data:
