version: '3.8'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
       MONGO_INITDB_ROOT_USERNAME: osher
       MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      
    depends_on:
      - zookeeper

  web:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - kafka

  kafka_consumer:
    build:
      context: .
      dockerfile: dockerfile.kafka_consumer
    depends_on:
      - kafka
      - mongo

volumes:
  mongo_data:
